### ISSUE TITLE
Problem encounted during roslaunch roomblock_bringup roomblock.launch

### ISSUE THREAD

**Issue by Gambit30** [tork-a/roomblock#10]
resource not found: create_description
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/pom/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share
XacroException('resource not found:',)
when processing file: /home/pom/catkin_ws/src/roomblock/roomblock_description/urdf/roomba500.urdf.xacro
included from: /home/pom/catkin_ws/src/roomblock/roomblock_description/robots/roomblock.urdf.xacro
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/kinetic/lib/xacro/xacro '--inorder' '/home/pom/catkin_ws/src/roomblock/roomblock_description/robots/roomblock.urdf.xacro'] returned with code [2]. 

Param xml is <param command="$(find xacro)/xacro '--inorder' '$(find roomblock_description)/robots/roomblock.urdf.xacro'" name="robot_description"/>
The traceback for the exception was written to the log file

I received this above message when I launch the room_block_bringup roomblock.launch. Anyone know how to solve this issue? Thank you in advance.

**Comment by 7675t** [comment]
You are trying to build and run with source code. You need to run rosdep to resolve dependencies like:

$ roscd
$ rosdep install -r —from-path ../src —ignore-src

Or you can also use released package in Indigo and Kinetic, witch should resolve the dependency automatically.

**Comment by Gambit30** [comment]
Thank you. I have solved the issue

**Comment by jiaweiwuwu** [comment]
still not solve this problem
