### ISSUE TITLE
Problem installing roomblock

### ISSUE THREAD

**Issue by RomanROBER** [tork-a/roomblock#6]
I am new to ROS and Ubuntu. Thank you for the tutorial but Im having trouble installing the roomblock, when I run ./install_roomblock.sh I got this error : 

![image](https://user-images.githubusercontent.com/29309956/26983705-fe1aa5a6-4d3c-11e7-8b38-1259145f712d.png)

Im running Ubuntu Mate 16.04 on a Raspberry 3 B+ and have ROS Kinetic. Is there any Troubleshooting for this issue? 

Regards
R

**Comment by 7675t** [comment]
I don't use Ubuntu Mate, but I have encountered similar problem. Some binary in libraspberrypi-* conflict other system packages. In general, you can avoid  this as: 

```
$ apt download libraspberrypi-bin-nonfree
$ sudo dpkg -i --force-overwrite libraspberrypi-bin-nonfree.deb
```

I expect someone on upstream solves this problem eventually.

**Comment by RomanROBER** [comment]
Hello again, I tried your solution but now I got another Problem:

![image](https://user-images.githubusercontent.com/29309956/27032932-56f9370a-4f77-11e7-9c87-a570b75e7f29.png)

Thank you very much for your help 

Regards
R

**Comment by 7675t** [comment]
Please specify the file (libraspberry-pi-bin-nonfree_1.2brarabra.deb) you just downloaded.

**Comment by RomanROBER** [comment]
You were right :) 

I had some trouble with rtl8192cu driver and with the kernel so I installed everything separately 
![image](https://user-images.githubusercontent.com/29309956/27075183-9d1aaa68-5029-11e7-99ec-300ac3057e81.png)
 
Then I ran the installer again and it prints that is installed then I did:

`$ sudo apt upgrade` 
and reboot


So now when I try to run roomblock_bringup roomblock.launch it shows that is not installed or found.

![image](https://user-images.githubusercontent.com/29309956/27075865-c3ae1622-502b-11e7-89d3-d211f40b7c6d.png)

Regards,
R

**Comment by 7675t** [comment]
The install script doesn't create workspace and get the source code.
Please consult README.md to create your own workspace, get the source code, and build it.

```
$ mkdir -p ~/catkin_ws/src
$ cd ~/catkin_ws/src
$ git clone https://github.com/tork-a/roomblock.git
$ cd ~/catkin_ws
$ rosdep install --from-paths src --ignore-src -r -y
$ catkin_make
```

**Comment by RomanROBER** [comment]
Many thanks for the help!

now I made the Workspace :

![image](https://user-images.githubusercontent.com/29309956/27123253-96d6b808-50ed-11e7-8e58-43087d4ff9a3.png)

But when I try to run :
`$  roslaunch roomblock_bringup roomblock.launch ` 

I got : 
![image](https://user-images.githubusercontent.com/29309956/27123346-daef0b4e-50ed-11e7-8860-6ef4ec935d35.png)

Am I missing something else? 

Regards,
R

**Comment by 7675t** [comment]
You need to source setup.bash to use the workspace.

cd ~catkin_ws
source devel/setup.bash

And I strongly recommend to take a look on ROS wiki to get basic concept of workspace and packages.
 
http://wiki.ros.org/ROS/Tutorials

**Comment by RomanROBER** [comment]
Thank you for the fast answer and for the suggestion this is my first Project with ROS. I will read and practice more.

Now is working but can I use the roomblock with the Serial Port (ttyAMA0) instead of the USB cable?
 I have my Roomba connected to the Serial port.

Regards,
R

**Comment by 7675t** [comment]
I haven't tried it yet. I believe there is no difference between usb serial and on board serial. I'm grad if you try it.

Edit this file to change the port from /dev/roomba to /dev/ttyAMA0. 

roomblock_bringup/launch/include/real_roomba.launch.xml

Or making a symlink from your device file to /dev/roomba may be easier.
